from src.rewarders.rel_range_rewarder import RelativeRangeLogReward, RelativeRangeDataStore, RelativeRangeData
from src.rewarders.docking_corridor_rewarder import DockingCorridorReward, DockingCorridorDataStore, DockingCorridorData
from src.rewarders.quadratic_time_penalty import QuadraticTimePenalty, TimeDataStore, TimeData

from src.rewarders.rewarders import get_rewarders